
<img src="img/intro/python_logo.png">


In [1]:
print("Hello world!")

Hello world!


## Contenido

1. Tipos de datos
2. Estructuras
3. Indexación
4. Ejercicios

### 1. Tipos de datos 

Estos son los tipos de datos básicos.

* Números enteros: -1000, -2, 0, 33, 1234
* Números decimales: -1.2, 0.3, 334.34
* Cadenas de carácteres (*String*): "Hola!"
* Booleanos: True, False.


In [2]:
type(85.5)

float

### 2. Variables

Los datos que se utilizan dentro de los programas se guardan dentro de lo que se llaman variables.

Tienen tres características que las definen completamente: nombre tipo y valor.

Pueden tener un tipo de los que hemos visto anteriormente o de tipos complejos como veremos a continuación.

### 2. Estructuras de datos

Las estructuras básicas de Python para organizar los datos son las listas y los diccionarios.



**Listas**

Es una colección ordenada de elementos, no tienen por que ser del mismo tipo.

Si nos fijamos las listas son tipos de datos complejos ya que estan formados de otros tipos mas sencillos.

In [3]:
lista = []
lista2 = [1, 2, 4]
lista3 = ["uno", "dos", "tres"]
lista4 = [1, "dos", 3.2]

El operador ```in``` permite comprobar si un elemento esta dentro de una lista

```python
4 in [3, 4, 5, 6]
True
0 in [3, 4, 5, 6]
False
```

Podemos añadir elementos al final de las listas mediante el nombre de la lista y el sufijo ```nombre.append()```.

También podemos concatenar listas usando el operador ```+```.

```python

a = [1, 2, 3]
b = [4, 5, 6]
c = a+b
print(c)
[1, 2, 3, 4, 5, 6]

a.append(4)
print(a)
[1, 2, 3, 4]
``` 

**Diccionarios**

Estructuras clave, valor. Los diccionarios son una manera limpia de asignar un valor a una clave. Ello nos permite recuperar un valor de forma rapida dada la clave. Se crean usando los curly brackets.
```python
mi_diccionario = {}
```
Creo la clave contacto y le asigno un nombre
```python
mi_diccionario['contacto'] = 'Juan'
mi_diccionario['telefono'] = 123456
mi_diccionario['edad'] = 30
```

Accedo al valor de la clave 'telefono'

```python
print(mi_diccionario['telefono'])
123456
```

In [1]:
dict1 ={}
dict2 ={
    "key1": ["uep!", "com anam?"],
    "key2": "valor 2",
    "key3": 3
}

In [6]:
notas = {'Pedro': 9, 'Maria':10, 'Luis':8.5}

# que nota ha sacado María ?


# Qué pasa si intentamos acceder a un nombre que no existe?



# Prueba ahora con notas.get('pepe'), ves alguna diferencia?




## 3. Indexación

Como acceder a los elementos de una lista.

* Consultar un elemento.
* Consultar un sub-array.
  * Por posición.
  * Vector de booleanos.

## Consultar un elemento de un array

In [7]:
array = ["Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo"]

La lista empieza en la posición 0.

Así que, para consultar el primer elemento hacemos lo siguiente:

In [8]:
array[0]

'Primero'

**¿Cómo consultariamos el quinto elemento?**

### Acceso inverso

¿Cómo consultamos el último elemento de un array del que no conocemos su longitud?

In [ ]:
array[-1]

Siguiendo esta lógica, ¿Podemos consultar el antepenúltimo sin saber la longitud de la lista?

## Accesso a sublistas

Tècnicas: 
* Slicing
* Vector de booleanos

### Slicing

El slicing se aplica a los vectores siguiendo la siguiente lógica. El resultado es un vector con los elementos seleccionados.

```{python}
sublista = lista[start:stop:step]
```

* **start** Posición de la lista original dónde empieza la sublista. Si no se indica és 0.
* **stop**  Posición de la lista original hasta donde seleccionar. Si no se indica és la última posición.
* **step**  Incremento entre cada índice de la selección, por defecto 1.

Veamos un ejemplo. Para seleccionar desde el segundo elemento al quinto podriamos hacer como sigue:

In [9]:
array[1:5]

['Segundo', 'Tercero', 'Cuarto', 'Quinto']

Usos típicos:
* Seleccionar los n primeros (o últimos) elementos de una lista.
* Eliminar los primeros (o últimos) valores de una secuencia.

In [10]:
array[:5]

['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto']

In [11]:
array[-5:]

['Cuarto', 'Quinto', 'Sexto', 'S\xc3\xa9ptimo', 'Octavo']

Eliminar los primeros (o últimos) valores de una secuencia. 

In [12]:
array[4:]

['Quinto', 'Sexto', 'S\xc3\xa9ptimo', 'Octavo']

In [13]:
array[:-4]

['Primero', 'Segundo', 'Tercero', 'Cuarto']

#### El step, ¿Para que sirve?

Indica cómo se incrementará el índice para la selección de la sublista. Por defecto vale 1, con lo que se seleccionan todos los elementos.

Si no queremos seleccionar todos los elementos, sólo los elementos de posiciones pares podemos hacer lo siguiente:

In [14]:
print(array)
array[::2]

['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto', 'S\xc3\xa9ptimo', 'Octavo']


['Primero', 'Tercero', 'Quinto', 'S\xc3\xa9ptimo']

Su uso más extendido és para invertir el orden de una lista. Si durante la selección de la sublista incrementamos el índice al revés se consigue este efecto.

In [15]:
array[::-1]

['Octavo',
 'S\xc3\xa9ptimo',
 'Sexto',
 'Quinto',
 'Cuarto',
 'Tercero',
 'Segundo',
 'Primero']

### Vector de booleanos

**Atención!** Sólo para Numpy y Pandas.

In [16]:
import numpy as np
array = np.asarray(array)

In [17]:
boolvect = [False]*8
boolvect

[False, False, False, False, False, False, False, False]

**IMPORTANTE:** El vector de booleanos debe tener la misma extensión que el array que se quiere indexar.

In [18]:
array[boolvect]

array([], dtype='|S8')

In [19]:
boolvect[7] = True
array[boolvect]

array(['Octavo'], dtype='|S8')

In [20]:
boolvect[4] = True
array[boolvect]

array(['Quinto', 'Octavo'], dtype='|S8')

In [21]:
boolvect

[False, False, False, False, True, False, False, True]

Una manera de obtener un array de booleanos és mediante una comparación. En el siguiente ejemplo calculamos un array de booleanos con valor ```True``` en todas las posiciones del array con el valor "Primero".

In [22]:
array=="Primero"

array([ True, False, False, False, False, False, False, False])

In [23]:
array1 = np.array([1,2,3,4,2,5])
array1

array([1, 2, 3, 4, 2, 5])

In [24]:
array1==2

array([False,  True, False, False,  True, False])

## 4. Ejercicios

A continuación tenemos los datos que utilizaremos para realizar los ejercicios.

In [25]:
lista = ["Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo"]
nparray = np.array([1,4,6,"BUSCAME",89,2,4,5])
diccionario = {
    "key1": [],
    "key2": [1, 2, 3],
    "key3": 90.6
}

**1) Consulta el tercer elemento de "lista".**

**2) Consulta el elemento asociado a la cadena de caracteres "key3" de "diccionario".**

**3)  Consulta el penúltimo elemento de "lista".**

**4) Obtén la lista con los 3 primeros elementos de "lista".**

**5) Obtén la lista con los 4 últimos elementos de "lista".**

**6) Indexar con booleanos. A partir de "ndarray" crea un array con el elemento "BUSCAME".**

**7) Obtén la lista con los elementos pares de  la lista "lista".**

Resultado buscado: ['Segundo', 'Cuarto', 'Sexto', 'Octavo']